### ISSUE TITLE
Start programs not closing

### ISSUE THREAD

**Issue by terrymacdonald** [terrymacdonald/DisplayMagician#75]
Hi @sk666 and welcome back!

I'm going to split these two issues up so I can track them separately. I'll paste your second issue below so I can refer to it to make the new issue:

2- My second issue is something that you fixed for me in a previous a couple of months ago but problem is back with the latest version: 4 apps are supposed to launch when I start a game, but when I quit the game, the 4 programs are not fully closed as they are supossed to be. Sometimes 1 app still running after the roll back, sometimes 2 programs are running. I don't know if you can fix it again, I don't know if DM always check in the active process list if all of the 4 apps are still running during the roll back to force them to "shutdown".

Thanks
Terry

_Originally posted by @terrymacdonald in https://github.com/terrymacdonald/DisplayMagician/issues/74#issuecomment-1003780237_

**Comment by terrymacdonald** [comment]
After reviewing the game shortcut config, it looks like this is a misconfiguration and is not a bug. Please see #74 for more information. I will close this issue for now, but feel free to reopen if you are still having an issue after making the changes I've suggested in issue #74.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry, take a look to my comment in the issue #74, #75 need to be reopened as well.

Thank you

**Comment by terrymacdonald** [comment]
Reopening until further investigations continue.

**Comment by terrymacdonald** [comment]
@sk666 Great news. I did indeed find a bug in the StopProcess function that was preventing the stop from working in some situations. If the program being stopped didnt have a window associated with it, it probably wouldn't be stopped. This has now been fixed in the codebase.

I have also managed to implement some extra cool multithreading/single instance/named pipes coolness that should speed up DisplayMagician being used in the system tray.

I've included a test build for you to install and try. Please check if this makes your issues disappear. Also see if you can break it in other ways, as I need to ensure that this new code is robust.
[DisplayMagicianSetup-v2.1.5.33.zip](https://github.com/terrymacdonald/DisplayMagician/files/7806772/DisplayMagicianSetup-v2.1.5.33.zip)

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

I tested this build (2.1.5.37), and I had weird problems during install (I forgot to say that I see some of them earlier when I installed the 2.1.5.5 but some of these error are new today (see attached screenshot). I was not able to take all of the screenshot because after the installation, I needed to reboot my computer with the physical restart button on my computer because everything was gray and computer was unresponsible, the CTRl+ALT+DEl dosne't worked too.

So after this, I tried to install it again to take these screenshot, and this built dosen,t work at all. If I try to launch ATS with DM shortcut on my desktop, a popup appear "display magician is loading", but notting appear after that, it dosen't start any progam, it did not switch to the surround profile.

I tried to switch to surround profile display in the display profile windows and it dosn't work anymore if I select it and click on apply button :(

![01](https://user-images.githubusercontent.com/29050341/148076083-826a8fba-63ff-46e3-a13d-a06e85d8ecfa.PNG)
![02](https://user-images.githubusercontent.com/29050341/148076085-f3887bd1-dc58-4b9a-8554-cbee75583f99.PNG)
![03 if i click on Ok button on screenshot 02](https://user-images.githubusercontent.com/29050341/148076086-63249a3f-9fb8-4f2e-82c0-4ac48391302f.PNG)

**Comment by terrymacdonald** [comment]
@sk666 It looks like the installation only half finished, and is causing issues when installing over the top again.

I suggest going into your 'Add & Remove Programs' part of windows settings, and uninstalling DisplayMagician from there. Reboot your computer, and then reinstall the test version 2.1.5.37 again for me. 

IMPORTANT: Another user has told me that the system tray / desktop background menus are both broken in this release, so when you do testing, please only use the Shortcut Library window or Desktop Shortcuts for running shortcuts. I'll try fixing the system tray / desktop background menus in the next test release.

If you want to downgrade your version of DisplayMagician back to v2.1.5.5, then you will need to go back into your 'Add & Remove Programs' part of windows settings, and uninstalling DisplayMagician from there. Reboot your computer, and then reinstall the test version 2.1.5.5 again to get back to that version.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry, 

I unistalled it, please see my other comment on issue #74.

Thank you

**Comment by terrymacdonald** [comment]
@sk666 Can you please test loading notepad.exe in one of your new game shortcuts as a start program, and then please set it to close when finished. That will test that the closing is actually happening now, and then we'll be able to close this issue and focus on the other one.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hmmmm, did you try it with a shortcut that was not ATS or ETS?

Thanks
Terry

**Comment by sk666** [comment]
yes I tested with the Britannic game.

thank you

**Comment by terrymacdonald** [comment]
Cool. Ok, I'll check out all those results later this evening and try and
figure out where there could be an issue. I think it might take me a while
to understand the results of all the testing. I'll come back to you with
some Moore information as soon as I can.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sk666 Can you please try this build next? The install should work better this time as I spent a fair bit of time trying to iron out some of the issues. It will ask to reboot at the end of the install process now (I think that's best to make sure it works for ppl).

[DisplayMagicianSetup-V2.1.5.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/7820559/DisplayMagicianSetup-V2.1.5.50.zip)

**Comment by sk666** [comment]
Hi,

like I said in issue #75, steam dosen't launch by itself with build .50 when I try to launch ATS with shortcut window in DM, but it seem to work with previous build if I remember correctly.

Thank you

**Comment by terrymacdonald** [comment]
Hi @sk666

Great to hear that issue #74 is as fixed as it can get. Sorry to hear the
taskbar still moves in surround mode.

What do you mean about Steam doesn't launch itself with ATS? If you have
ATS installed in the Steam launcher, then you should simply need to select
ATS from the list of games down in the shortcut editor, and it will run
Steam as part of the launch process.

DisplayMagician does not support running Steam.exe as a start program. That
will mess up the DisplayMagician detection mechanism, and potentially so it
running the Game properly.

If you need Steam to start when your computer starts, then you can get
Steam to start when your computer does by opening Steam and going to Steam
> Settings > Interface and enabling the 'Run Steam when my computer starts'
option. That's what I do.

Thanks
Terry

**Comment by sk666** [comment]
oh ok so If I need to start a steam game, I need to launch steam before I run the DM shortcut? May be I didn't udernstand it before, I thought that steam will be automatically start if I run a shortcut who have a steam game. I don,t talk about steam in the add program tab, but in a previous build (thinh .37), if I start ATS from the shortcut it start steam a couple second before start the game beacause Dm see that is a steam game. And he did that even if I didn't add steam.exe in the add program list.

Am I right?

**Comment by sk666** [comment]
If I create a shortcut of a steam game on my desktop (from Steam itself), this shortcut launch steam even if steam is not previously started so I tought that DM did the same thing, may be I am wrong or very lucky to have this feature in the past with DM.

**Comment by terrymacdonald** [comment]
@sk666 you know I've never actually tested Steam without it already
running! I'll test it myself today, but I expect it should work fine (as it
seems to do for you).

DM starts Steam games through the URL handler (steam://rungameid/111111/)
which is exactly how Steam starts games from it's own desktop shortcuts.
That does actually start Steam (or reuses the same Steam if it was started
already) and then Steam runs the game.

DM uses that same process when it runs Steam games, so you're right that
Steam doesn't need to be started. Its just out makes it faster.

How I use DM is that I tick the 'start DisplayMagician and minimise it when
computer starts' checkbox on the main DM page so that DM runs when the
computer is started. I also set Steam to run when the computer starts.
Doing both these things means that my DM game shortcuts start up faster as
Steam and DM are already running as they always start up when the computer
is started.

Does that make sense?

Thanks
Terry

**Comment by terrymacdonald** [comment]
> Hi,
> 
> like I said in issue #75, steam dosen't launch by itself with build .50 when I try to launch ATS with shortcut window in DM, but it seem to work with previous build if I remember correctly.
> 
> Thank you

I'm sorry I don't understand what you mean by this. I have a few questions listed below to understand it better:

- Are you saying that that when you try to launch the ATS from the DM shortcut library window it won't run at all? Meaning that when you doubleclick on the ATS shortcut nothing happens? 
- Does the shortcut have an 'warning' symbol over it? 
- Does the 'Run' button show up when you select the ATS game shortcut?
- Does the ATS shortcut start doing things when you select the ATS game shortcut and then press the Run button? Or does it do nothing at all?
- Do other Game shortcuts run ok when you start them from the DM shortcut library window? e.g. Britannica?
- Do you have any start programs running with ATS? If so, can you please make a copy of the ATS game shortcut, and then remove the start programs from the copy? Then run the copied game shortcut, to see if ATS will start without those start programs.

Please tell me the answers to each of those questions listed above as it will help me try to figure out what is still going wrong.

Thanks
Terry

**Comment by sk666** [comment]
•	Are you saying that that when you try to launch the ATS from the DM shortcut library window it won't run at all? Meaning that when you doubleclick on the ATS shortcut nothing happens? No, When I do that, DM activate surround, DM starts programs in the tab « chosse what happen before » but he dosen’t launch the steam game, even if steam is already open, and because nothing happen here, no game start after that. Tried with Britannica game and ATS, same behavior to both game.

•	Does the shortcut have an 'warning' symbol over it? No :)

•	Does the 'Run' button show up when you select the ATS game shortcut? Yes, and it is visible too with Britannica game.

•	Does the ATS shortcut start doing things when you select the ATS game shortcut and then press the Run button? Or does it do nothing at all? Yes, see my first answer.

•	Do other Game shortcuts run ok when you start them from the DM shortcut library window? e.g. Britannica? Same behavior than ATS shortcut, the games won’t launch and steam not open too. 

Interisting fact, DM seem to freeze here because the cancel button in the attached picture is not working. Does it should be work? I need to kill DM in task manager so, can you remember me where are the log on the C drive please? Because he’s freezing, I can’t collect them with DM settings but I can take them by the windows explorer, my PC dosen’t freeze at all hopefully.

•	Do you have any start programs running with ATS? If so, can you please make a copy of the ATS game shortcut, and then remove the start programs from the copy? Then run the copied game shortcut, to see if ATS will start without those start programs. Yes he have, I didi it and same behavior. « chosse what happen before » tab is empty, DM switch to surround, the DM window with the cancel button appear (the windows of the attached picture), and that’s it. Steam won’t launch and game won’t launch, even if steam is previously launched or not, it’s not an issue related to ATS only, seem to do that with all of my steam game. If I remember correctly, this behavior won’t happen with previous build, but i’m not 100% sure, may be 80% sure. I am little bit lost with all of these test but I can try with an earlier build if you want too.

Intesting fact #2, DM dosen’t launch anygame even, if they are not related to steam at all, I tried with 2 local games on my C drive, for reference, these games are « GTA 4 » and "the next car game free demo" anbd same behavior happen.

![DM cancel bouton not working](https://user-images.githubusercontent.com/29050341/148648181-c77d1e95-a217-408c-b914-43495624ecdc.PNG)

**Comment by terrymacdonald** [comment]
@sk666 Hmmmm. So the problem at the moment is that Steam doesn't launch the game? I wonder if there is a problem with the steam URL handler on your PC?

To test that, I need you to create a Desktop Shortcut for ATS through Steam. Can you please:
- Open Steam
- Go to the Library page
- Right click on **ATS**, then select **Manage** > **Add Desktop Shortcut** (My example is for another game)
![image](https://user-images.githubusercontent.com/5721772/148662306-7ad58e17-99b4-4fec-8088-85da2dd3a268.png)
- Save the desktop shortcut to the desktop
- Close the Steam window
- Try to run ATS from the steam desktop shortcut you just created

If this does NOT work and the game fails to load, then the problem is with steam. If this does work and ATS loads, then we need to do further testing.

Can you also please install this test version I just created? It changes DisplayMagician logging so that it will save the last 4 log files and will include them in the Support ZIP file, which should make it easier for all users from now on.
[DisplayMagicianSetup-v2.2.0.4.zip](https://github.com/terrymacdonald/DisplayMagician/files/7834114/DisplayMagicianSetup-v2.2.0.4.zip)

The DisplayMagician.log files are in `C:\Users\<yourname>\AppData\Local\DisplayMagician\Logs` if you ever need to get them.

I'll have a look at the Cancel button. It is quite likely that the Cancel button doesn't work since I changed the application to always running as a SingleInstance to make it faster to start. That required a bit of structural change in the background, and the Cancel button is one I forgot to change.

It's REALLY interesting about the software not being able to run any game what so ever, even exe's. That is a very strange one. I wonder if Windows or something else is blocking DisplayMagician from running? Can I ask what Antivirus/Antimalware software you are running? 

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sk666 I've found a bug! The bug was in the way that the RunShortcut thread was handing data to the UI updating thread. It would get 'locked', and would just stop the shortcut from running properly. The code that was broken was specifically for the updating the systray icon, and that happens for the first time just before the the main game. 

I've made some changes in the codebase to fix that, but that in turn caused issues with the cancel button! So now I'm in the process of updating that (and that in turn has cased issues with processing Windows Toast buttons \o/. Everything is so interrelated nowadays.

This means I should be able to get your games loading again in a day or so. 

I'm trying to test all the ways I can open or edit something as I need to make sure that the move to a single instance, threaded execution model hasn't broken some more things. It will make the app more responsive and faster to use once all these little bugs are ironed out, but it might take a few versions to get all the bugs identified.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

I tested my steam librariees 2 days ago with the same test that you propose and yes, my steam libraries works fine (sorry I forgot to tell you that I did this test earlier). 

I tested DM built .50 on the laptop of my gilfriend (even if she dosen't have an external display) and it fails to launch any local game so I think you are on the right way with the bug that you have discovered, good job :)

Do you still need a test from me with the build 2.2.0.4?

Take your time to fix this, I hope that you will be able to fix the minimized application that are not properly closed if they are minimized to system tray.

Thank you

P.s It's a good idea to save the last 4 logs, thank you very much for this :)

**Comment by terrymacdonald** [comment]
Hi @sk666

No, don't bother with 2.2.0.4. I'll hopefully have a new build in a few
days that fixes the issue with starting applications and games.

I'm currently taking some time to map out the flow of logic and calling
logic for the new multithreaded model we've moved to, and I'll be going
through each statement to figure out where any issues may be.

This could take a little while to sort out ☹️.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Found a couple of issues with how I was using threads that I sorted. I'm hopeful that fixed the underlying problems. Turns out threads are challenging to implement...

I also think I now have a solution for the parallel use of NVIDIALibrary and WinLibrary. It looks like main DisplayMagician UI thread was sometimes trying to update the current display profile while another thread was applying a new display profile. I've tried to put in a solution for that which does updating the current display profile until the apply profile has returned.

I've also speed the cancel button for monitoring shortcuts and it works again, but currently having issues with the buttons in the windows notifications... Once that problem is cracked I should be able to make a new test release.

Thanks
Terry

**Comment by terrymacdonald** [comment]
OK @sk666 - I *think* I finally cracked this last night. I had to transition from the original toast notification library I was using to the newer Microsoft one. I think this will work better in the long run, as it will be updated by Microsoft to support their windows Toast improvements as Windows dev continues.

In any case, can you please install this test v2.2.0.41 please? And see if all your errors have disappeared? Please report back with any errors you find (screenshots too please if possible) and of course upload the support ZIP file if you have any errors too.

[DisplayMagicianSetup-v2.2.0.41.zip](https://github.com/terrymacdonald/DisplayMagician/files/7866290/DisplayMagicianSetup-v2.2.0.41.zip)

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

thank you for your work. Unfortunately, DM is not ablke to close program vene if they are minimized or not, and DM is not able to revert back to my previous display profile. Good news, with the build 2.2.0.41, steam launch again when I run my ATS shortcut and it launch the game too, so at least, I can play it again with the shortcut, but stuck in surround mode when I quit the game. There is the log.

Thank you 

[DisplayMagician-Support-20220114-0916.zip](https://github.com/terrymacdonald/DisplayMagician/files/7870914/DisplayMagician-Support-20220114-0916.zip)

**Comment by terrymacdonald** [comment]
@sk666 What make and model of NVIDIA video card do you have again? Is it a 3080Ti?

What version of the NVIDIA driver are you running? Have you tried v511.23 at all?  If not, can you please try to download and load the stock NVIDIA driver from NVIDIA (please don't use any custom drivers).

@FormelLMS has found a problem where the NVIDIA driver won't let us turn off Surround mode. I wonder if that's a similar problem to what you are experiencing? He will be sending through some logs over the next few days, and when I get a chance to review them, it should shed more light on what is wrong.

I will send you some instructions on using NVIDIAInfo to perform some tests later today or tomorrow that will clarify where the issues lie.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

yes I tried this morning with 511.23 and the problem still occurs, it's the same than @formeILMS. I have a GTX 970.

thank you

**Comment by sk666** [comment]
![stuck in surround mode](https://user-images.githubusercontent.com/29050341/149626509-61502e63-ef02-4828-ba15-2b7962501bd8.PNG)

**Comment by sk666** [comment]
I forgot to say, I take my nvidia driver from geforce experience, and I choosed fast install or something like that, not the custom. Is it okay?

**Comment by terrymacdonald** [comment]
Yep, that's perfectly fine. That's how I do it too.

Terry

**Comment by terrymacdonald** [comment]
@sk666 I have some NVIDIAInfo instructions for you to run:

Please download the attached NVIDIAInfo to your computer: 
[NVIDIAInfo-v1.3.9.zip](https://github.com/terrymacdonald/DisplayMagician/files/7877853/NVIDIAInfo-v1.3.9.zip)

Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create your surround display layout with some of your screens (surround):
- Save the first surround display as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout (regular):
- Create a regular display layout with different screens (turn some of the original screens off, and move other ones around, and change the primary monitor)
- Save the second windows display as `NVIDIAInfo save regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)

Next swap back to the superdisplay display layout:
- Load the first windows display as `NVIDIAInfo load superdisplay.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal regular.cfg` (we DO NOT want it to be equal)

Next swap back to the regular display layout:
- Load the second windows display as `NVIDIAInfo load regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save regular-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- regular.cfg
- regular-reload.cfg
- NVIDIAInfo-regular-save.log
- NVIDIAInfo-regular-reload.log

Lets see what we get in the logs.

Thanks
Terry

**Comment by sk666** [comment]
Hi terry,

thank you again for your support. I,m not sure that I understand what and where be theses instructions, I'm a noob in powershell. I created a folder temp2 in c: and extracted nvidiainfo in this folder. Then, in powershell, I typed this command: cd C:\temp2\NVIDIAInfo-v1.3.9

When you say:

    Save the first surround display as NVIDIAInfo save surround.cfg (wich tools should I use do to this? nvidia control panel, DM or with a powershell command? 
    Rename the NVIDIAInfo.log file to Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log" Is it a powershell command? if yes, does cd C:\temp2\NVIDIAInfo-v1.3.9 is correct?
    Check if the first windows display config is equal with NVIDIAInfo equal surround.cfg (we want it to be equal) What do you mean by equal?

Thank you and sorry for this misunderstanding.

Thank you

**Comment by terrymacdonald** [comment]
Hi @sk666,

Yep. You just need to paste the bits in grey e.g. *Rename-Item -Path
"NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"* into the
powershell window. Rename-Item is a powershell command.

What do I mean by equal? NVIDIAInfo has a command to compare the current
config to the one in a cfg file. I'd like you to copy the results of the
equality test e.g. copy the text shown when you run the command.

Hope that clears things up.

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com

**Comment by sk666** [comment]
Ok I had a powershell error when I run this commamd: NVIDIAInfo save surround.cfg I dont have tge exact error with me right now but if I'm remember correctly, it say that he dosen't recognize this command but it's not fully unrecognized...do you ever see this error? I dont understand it because I am in the nvidia folder when I typed this. If you need a screenahot, I can provide one or two tomorrow.

Thank you

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by terrymacdonald** [comment]
Did you unzip the  NVIDIAInfo zip file you downloaded? NVIDIAInfo is shared
as a zip file, and you need to extract the zip file in order to use it. You
should open a windows explorer window and visit C:\temp2\NVIDIAInfo-v1.3.9
in it. You should see  NVIDIAInfo.exe and other files in there.

You then do exactly as you described before.... open a Powershell window,
and then enter  cd  C:\temp2\NVIDIAInfo-v1.3.9 and you should now be in
the  C:\temp2\NVIDIAInfo-v1.3.9  folder. If you type NVIDIAInfo on its own
then press enter, you should see the NVIDIAInfo help message. If you see
that, then you can continue with the tests.

Hope that helps

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com

**Comment by FormelLMS** [comment]
I have to put a .\ before the commands in powershell. Hope this helps perhaps. 

@terrymacdonald your mobilphone number is Applied in this Thread.

**Comment by terrymacdonald** [comment]
Thanks @FormelLMS!. Mobile removed :)

**Comment by sk666** [comment]
Hi terry,

I'm sorry but I dont get the equal thing to check. Dont see what I need to check in the log. Secondly, I have a powershell error when I try to rename NVIDIAInfo-regular-save.log, the nvidiainfo.log dosen't exist, but the first one with the surround profile existed before so I don't understand what I have missed.

![image](https://user-images.githubusercontent.com/29050341/149942035-8e2f90a9-63f9-440f-934e-58908f5b51c2.png)

Do you understand what I have missed?

**Comment by terrymacdonald** [comment]
@sk666 that Rename-Item command changes the name of the file from one name to another. The first command you ran worked as it renamed the NVIDIAInfo.log file to NVIDIAInfo-surround-save.log. This meant the NVIDIAInfo.log file wasn't there, so the 2nd command didn't work.

That's the reason my tests were in that exact particular order. Each test relied on the previous tests being run. The output of one test was sometimes used as an input to the next tests.

OK - now to the problem at hand :). Thanks to @erbkaiser I've been doing some other tests in the background, and I've got a hunch that the EnableMosaicTopo error we were getting may be a residual error left over from some of our earlier bugs. So I'd like you to perform the following tests for me:

- Please install DMv2.2.0.52 for me: 
[DisplayMagicianSetup-v2.2.0.52.zip](https://github.com/terrymacdonald/DisplayMagician/files/7887117/DisplayMagicianSetup-v2.2.0.52.zip)

- Please create a brand new Surround Profile and a brand new Triple Screens profile(non-surround).
- Please try to swap between those two new profiles and only those two new profiles (do not use any old profiles at all).
- See if those two new profiles swap without any issue
- Please upload a support ZIP to this issue

I'm hoping that all of the other fixes we have come up with recently will mean that the two newly created profiles will work. I think that the other profiles were created when I still had some multithreading issues, and that may have introduced errors to the display profiles we made then. That of course means that were broken when they were made, which means they will never work (there isn't a way to fix them).

Hopefully, recreating them both again new will mean that they have the correct data in them, and hopefully they will just start working again! Your tests will help say if that's right.

Thanks
Terry

Thanks. 
Terry

**Comment by sk666** [comment]
Hi terry,

I understand but why it dosent create the second nvidiainfo.log the second time? I did all the steps in the exact order.

I tried the build .52 with new profile but same thing again, I tried to switch from surround to normal profile but it dosent work. But I can switch from normal to surround without problem.

I think it will be useful if I can did your test with your nvidia tool but unfortunately, I did not understand well what you said. May be a problem with english language or a misunderstanding how powershell works or how your nvidia tool work. I read all the instructions carefully but it dosent created a second nvidiainfo.log after I renamed the first one and it's this part that I dont understand.

Thank you

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sk666** [comment]
[DisplayMagician-Support-20220118-2305.zip](https://github.com/terrymacdonald/DisplayMagician/files/7893988/DisplayMagician-Support-20220118-2305.zip)

**Comment by terrymacdonald** [comment]
@sk666 Sorry I thought you were running the rename-item commands together! I understand your last comment now.

I've looked at the instructions I gave and I messed up with one of the commands, and that caused the missing log. I;ve updated the instructions below and hopefully I got them right this time 🙄. Sorry for the mixup my mistake caused.

As before, pllease complete the following instructions in this specific order:

Delete your previous cfg files just so I know they are newly created this time.

Create your surround display layout with some of your screens (surround):
- Save the first surround display as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout (regular):
- Create a regular display layout with different screens (turn some of the original screens off, and move other ones around, and change the primary monitor)
- Save the second windows display as `NVIDIAInfo save regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg` (<--- this line was wrong last time!)
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal regular.cfg` (we DO NOT want it to be equal)

Next swap back to the regular display layout:
- Load the second windows display as `NVIDIAInfo load regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save regular-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- regular.cfg
- regular-reload.cfg
- NVIDIAInfo-regular-save.log
- NVIDIAInfo-regular-reload.log

Lets see what we get in the logs.

Again sorry for the confusion I caused.

Thanks
Terry

**Comment by terrymacdonald** [comment]
I just looked at your DisplayMagician 2.2.0.52 logs. No change as you identified:

```
2022-01-18 23:00:31.2888|WARN|DisplayMagician.Program|NVIDIALibrary/SetActiveConfig: There was an error disabling the display mode. NvAPI_Mosaic_EnableCurrentTopo() returned error code NVAPI_MODE_CHANGE_FAILED
2022-01-18 23:00:31.2888|TRACE|DisplayMagician.Program|ProfileItem/SetActive: The NVIDIA display settings within profile Current NVIDIA Display Profile were NOT applied correctly.
2022-01-18 23:00:31.2888|ERROR|DisplayMagician.Program|ProfileRepository/ApplyProfile: Error applying the NVIDIA Profile!
```

Looks like we're going to have to wait for some help from NVIDIA :(. I've asked them the questions at least: https://forums.developer.nvidia.com/t/unable-to-disable-mosaic-mode-on-some-video-cards/200646

Apparently the person we need to speak to is on leave at the moment :).

Terry

**Comment by terrymacdonald** [comment]
Also, just so you know, I've checked to see how the old library we used to use (NvAPIWrapper) did the disabling of Mosaic/Surround profiles, and they used NvAPI_Mosaic_EnableCurrentTopo(0) too, just like we do. So we'd have the problem even if we still used NvAPIWrapper library rather than my NVIDIALibrary.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sk666 can you please uninstall 2.2.0.52, and then try 2.1.5.37 again please? I want to know if you still get this NvAPI_Mosaic_EnableCurrentTopo(0) error changing between the regular and surround display profiles. If that's the case, then I know it's nothing to do with the multithreaded singleinstance code I've added since 2.1.5.37 (which is now part of 2.2.0.52).

Should be able to use the config you have now.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

no problem with the confusion. With 2.1.5.37, even if I erease all my saved display profiles and create new ones, DM is not able to switch to surround or to switch to default profile. The apply button does nothing.

is it helping you? Do you still need nvidia log and if yes, with wich DM version?

Thank you

**Comment by terrymacdonald** [comment]
No logs needed. I think we have all the information we can get.

I have one more thing for you to try. Can you download and try the last
version of DisplayMagician that was previously swapping display layouts for
you?  I would like to see if an old version that was working ok before
still is working for you now.

The idea is to see if the NVIDIA driver has changed and stopped
DisplayMagician from working for you. If the older version that was working
properly in the past no longer works for you now, then we know that it is
the NVIDIA driver, or something on windows that has changed to do it
working.

If the older version that was working properly in the past still works for
you now, then we know that it's something in the latter versions of
DisplayMagician that is the cause.

Can you please give that test a go and see what you find?

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sk666 Note: you don't need to delete your current Configs, just rename the c:\Users\<username>\AppData\Local\DisplayMagician folder to something like c:\Users\<username>\AppData\Local\DisplayMagicianBackup, and then install and run the version of DisplayMagician you want to test. You can then rename the folder back when you want the old Configs back again.

**Comment by sk666** [comment]
Hi Terry,

I'm sorry to say that, everythings working fine before with the 1.1.4 relase and it is still the case today. DM is able to switch from the default profile to surround profil and vice-versa, if I create a desktop shortcut for the DM shortcut it work well, and issue # 75 is not as bad with the 1.1.4 relase, because DM is able to close all my minimized apps (except for Steam because I did not ask him to close it obviously). So everything works well with 1.1.4. IT's sad because you put a lot of work and time in the 2.x release :(

**Comment by terrymacdonald** [comment]
Hmmmm ok. Can you try v2.0.1 (the first 2.x I released)?

This is really good to know, as it means it's fixable by me! This is a good
thing!

Thanks
Terry

**Comment by sk666** [comment]
Hi terry,

for your information, 2.0.1.59 DM version is not able to switch between different display profile, so it seem that only 1.x version works on my system. 

Thank you

**Comment by terrymacdonald** [comment]
Ok. While we're testing with NVIDIAInfo, I'll also check out the
NvAPIWrapper library and compare it to my NVIDIALibrary and try to find
some differences.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oh @sk666, please check if this problem is now fixed too? I would like to close this issue so I know what I still have to work on.

**Comment by sk666** [comment]
Hi Terry,

Issue 75 still persist for me, even if the app is minimized to system tray or not. May be you should tkae a look to the code of DM 1.1.4, this issue was not present if I'm remember correctly. I don't know it will help you considering the fact that DM as changed a lot since this build.

Or may be I can build a script to close the app and make in sort that DM runs this script during the roll back.

Thank you

**Comment by sk666** [comment]
something new happens about this issue with build 179. DM refuse to close too, even if I try to right click on it on the system tray. It seems that he "think" that my game is running, but my game was closed since a couple of minutes. I'm am not able to open it after that, so I can not collect the log with the settings page. I will take it manually from the appdata folder instaed.

![impossible to close DM](https://user-images.githubusercontent.com/29050341/152643285-d91aaaa5-03c8-4985-b3df-7c0fbda1de4b.PNG)

[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/8008058/DisplayMagician.zip)

**Comment by terrymacdonald** [comment]
@sk666 Sorry this has taken some time for me to get back to fixing. I have been hard at work trying to get some new taskbar functionality added to DisplayMagician which turned out to be MUCH harder than I thought. I then took a little time off making DisplayMagician to recharge.

I've looked at your log files, and the first thing I can see that it successfully starts 2 programs, and then it thinks that it doesn't need to stop those two same programs as they have already been closed. From what you say, they aren't, so this is possibly a bug.

```
2022-02-05 07:51:52.1397|INFO|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: Starting 2 programs before the main game or executable
2022-02-05 07:51:52.1397|INFO|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: Starting Start Program process C:\Program Files\LGHUB\lghub.exe
2022-02-05 07:51:52.1587|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/TryExecute: C:\Program Files\LGHUB\lghub.exe was started successfully.
2022-02-05 07:51:52.1587|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/StartProcess: C:\Program Files\LGHUB\lghub.exe  has successfully been started by TryExecute
2022-02-05 07:51:53.1735|DEBUG|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: We need to stop C:\Program Files\LGHUB\lghub.exe after the main game or executable is closed.
2022-02-05 07:51:53.1735|INFO|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: Starting Start Program process C:\Program Files (x86)\SIMDashboardServer\SIMDashboardServer.exe
2022-02-05 07:51:53.1805|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/TryExecute: C:\Program Files (x86)\SIMDashboardServer\SIMDashboardServer.exe was started successfully.
2022-02-05 07:51:53.1805|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/StartProcess: C:\Program Files (x86)\SIMDashboardServer\SIMDashboardServer.exe  has successfully been started by TryExecute
2022-02-05 07:51:54.1893|DEBUG|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: We need to stop C:\Program Files (x86)\SIMDashboardServer\SIMDashboardServer.exe after the main game or executable is closed.
.......
2022-02-05 07:53:15.5064|DEBUG|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: We started 2 programs before the main executable or game, and now we want to stop 2 of them
2022-02-05 07:53:15.5064|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/ProcessExited: 5292 has exited and is not running. This means the process has finished!
2022-02-05 07:53:15.5224|TRACE|DisplayMagician.Processes.ProcessUtils|ProcessUtils/ProcessExited: 7692 has exited and is not running. This means the process has finished!
```

I'll test to see if I have some similar problems with my shortcuts to see if it's an issue here too. Watch this space.

The next thing I found was that the Display Profile could not be applied successfully. This line shows an example:

```
2022-02-05 07:53:19.4561|TRACE|DisplayMagician.Program|ProfileItem/SetActive: The NVIDIA display settings within profile Current NVIDIA Display Profile were NOT applied correctly.
2022-02-05 07:53:19.4561|ERROR|DisplayMagician.Program|ProfileRepository/ApplyProfile: Error applying the NVIDIA Profile!
```

Weirdly, the rollback logic says later on that it was fine:
```
2022-02-05 07:53:19.7108|TRACE|DisplayMagician.Program|ProfileItem/GetNVIDIAScreenPositions: Added a new Screen 4356 (1920x1080) at position 1920,0.
2022-02-05 07:53:19.7108|DEBUG|DisplayMagician.Program|ProfileRepository/UpdateActiveProfile: The NVIDIA profile 'Current NVIDIA Display Profile' is currently active (in use now).
2022-02-05 07:53:19.7108|DEBUG|DisplayMagician.Program|ProfileRepository/ApplyProfile: Display change attempt took 0:3.931 and was successful.
2022-02-05 07:53:19.7268|ERROR|DisplayMagician.ShortcutRepository|ShortcutRepository/RunShortcut: Error rolling back display profile to Current NVIDIA Display Profile
```

So I think that part needs a bit of investigation too. I'll spend some time looking at it tonight.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

Don't worry for the time it takes. May be I should give you another log because 2 weeks ago I changed my old GTX 970 for an RTX 3060. After the switch, I deleted all old DM configuration of the GTX 970 to statt new one with the RTX 3060. Do you think it's a good idea or if it does not matter?

I can say that the issue is still present but I don't know if I still have the "profile could not be applied" issue. Honestly I'm a little confuse too with this issue, I don't remember that it failed to switch between different profile. I have the same dual old screen but now both of them are connected with a DP to DVI cable ( in my old setup, I could not plug 2 screens with the same output on the 970). I will change them soon to buy 3 brand new screen so may be this new setup will work better with DM.

Let me know if you need new log with the 3060.

Thank you

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by terrymacdonald** [comment]
Yes please. Please send me a new Support.zip file.

And congrats on getting your hands on a new video card. Those are hard to
find at the moment. DisplayMagician will work better with newer monitors.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

i tested it again in the past days and the only program that is not closed after i quit my game is DM itself. I can not open it or close it, I need to go in the task manager to kill it. After that, I will be able to open it again. When I had this bug, I moved my mouse on the DM syst tray icon and there was a message who said that my game is running but it's not true, the game was closed, only steam was open.

See the attachement log with my new RTX 3060.

Thank you
[DisplayMagician-Support-20220320-1004.zip](https://github.com/terrymacdonald/DisplayMagician/files/8345854/DisplayMagician-Support-20220320-1004.zip)

**Comment by terrymacdonald** [comment]
Hi @sk666,

Yeah, I've been doing some testing myself recently, and it looks like there
is an issue with closing some software down at the end of the game. It
seems to only happen to some software, and I haven't quite figured out what
the scenarios are when that happens. Now that I've pretty much finished
working on the updates to NVIDIALibrary and WinLibrary, I'll turn my
attention back to figuring out this error. I've a feeling it may be a bit
tricky to lock down.

I have a couple of questions based on your answers above:

   - How do you run DisplayMagician to start ATS? From a desktop shortcut?
   Or from the Game Shortcut Window?
   - If you start DisplayMagician from a desktop shortcut, is
   DisplayMagician already running?
   - Do you have the 'Start DisplayMagician minimised in the notification
   area when the computer starts' enabled on the Main Application window?


Thanks

*Terry*

**Comment by sk666** [comment]
Hi Terry,

I start ATS with a desktop shortcut. I think the issue is different if I start ATS with the game shortcut window. May be this is the thing that have changed the behavior. I will try it again in the game shortcut windows tomorrow and I will keep you updated.

When I use my desktop shortcut, DM is closed and it is not running. I did not checked the box to run it on windows startup.

I hope that will help you to find this bug. I'm pretty sure that when I tried it last week, DM did not close any of the software that is supposed to close.

Thank you
________________________________

**Comment by sk666** [comment]
Hi Terry,

I was able to close DM if game is started from the Game Shortcut Window, and everything seem to work well. So the problem seem to be only with a desktop shortcut.

Thank you

**Comment by terrymacdonald** [comment]
Hi @sk666 ,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

It should work now when run from a desktop shortcut. I've checked on my test system and shortcuts work when started from the system tray, desktop shortcuts, command line or from the Shortcut Library window. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

Thank you for your hard work with DM. I tested some build since the build 2.3.0.35 and my issue still occur. If I start DM by a desktop icon, DM will not be able to close the started program (tab #3 Choose what happens before), DM will freeze after the game will be closed and I need to kill DM in the task manager. Hopefully,The bug is not present if I use the "run" button from the "game shortcut" menu in DM.

A little improvement in the 2.3.1.7: DM now detect that my game is closed when I quit it.

Also, another minor issue with 2.3.1.7, DM dosen't detect an icon for the default profile (the blue one, it only detect the green icon of the surround profile). See screenshot. When I create the default profile, it show me an error, not sure of the right words in english language but it's something like "The value was too low or to high for a int 32", see screenshot.

More details from this error:

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.OverflowException: La valeur était trop grande ou trop petite pour un Int32.
   à System.Convert.ToInt32(Double value)
   à DisplayMagicianShared.ProfileIcon.ToTightestBitmap(Int32 width, Int32 height, PixelFormat format)
   à DisplayMagicianShared.ProfileItem.get_ProfileTightestBitmap()
   à DisplayMagicianShared.ProfileItem.IsValid()
   à DisplayMagicianShared.ProfileItem.PreSave()
   à DisplayMagicianShared.ProfileRepository.AddProfile(ProfileItem profile)
   à DisplayMagician.UIForms.DisplayProfileForm.btn_save_as_Click(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DisplayMagician
    Version de l'assembly : 2.3.1.7
    Version Win32 : 2.3.1.7
    CodeBase : file:///C:/Program%20Files/DisplayMagician/DisplayMagician.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.15.867
    CodeBase : file:///C:/Program%20Files/DisplayMagician/NLog.DLL
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DisplayMagician.Shared
    Version de l'assembly : 2.3.1.0
    Version Win32 : 2.3.1.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/DisplayMagician.Shared.DLL
----------------------------------------
McMaster.Extensions.CommandLineUtils
    Version de l'assembly : 4.0.1.0
    Version Win32 : 4.0.1.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/McMaster.Extensions.CommandLineUtils.DLL
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Version de l'assembly : 7.1.0.0
    Version Win32 : 7.1.2.1
    CodeBase : file:///C:/Program%20Files/DisplayMagician/Microsoft.Toolkit.Uwp.Notifications.DLL
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Windows.ApplicationModel
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
System.Runtime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.Foundation
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.WindowsRuntime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.WindowsRuntime/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.WindowsRuntime.dll
----------------------------------------
Windows.Storage
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/system32/WinMetadata/Windows.Storage.winmd
----------------------------------------
DynamicComActivator
    Version de l'assembly : 0.0.0.0
    Version Win32 : 7.1.2.1
    CodeBase : file:///C:/Program%20Files/DisplayMagician/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
Newtonsoft.Json
    Version de l'assembly : 13.0.0.0
    Version Win32 : 13.0.1.25517
    CodeBase : file:///C:/Program%20Files/DisplayMagician/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.ValueTuple
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
PInvokeDelegateFactoryInternalAssembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 2.3.1.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/DisplayMagician.Shared.dll
----------------------------------------
EDIDParser
    Version de l'assembly : 1.2.5.3
    Version Win32 : 1.2.5.3
    CodeBase : file:///C:/Program%20Files/DisplayMagician/EDIDParser.DLL
----------------------------------------
YamlDotNet
    Version de l'assembly : 11.0.0.0
    Version Win32 : 11.2.1.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/YamlDotNet.DLL
----------------------------------------
protobuf-net
    Version de l'assembly : 3.0.0.0
    Version Win32 : 3.0.101.59408
    CodeBase : file:///C:/Program%20Files/DisplayMagician/protobuf-net.DLL
----------------------------------------
ValveKeyValue
    Version de l'assembly : 0.3.1.152
    Version Win32 : 0.3.1.152
    CodeBase : file:///C:/Program%20Files/DisplayMagician/ValveKeyValue.DLL
----------------------------------------
netstandard
    Version de l'assembly : 2.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Xml.Linq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Web
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
AutoUpdater.NET
    Version de l'assembly : 1.7.0.0
    Version Win32 : 1.7.0.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/AutoUpdater.NET.DLL
----------------------------------------
Microsoft.CSharp
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.resources.dll
----------------------------------------
NHotkey
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.1.0.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/NHotkey.DLL
----------------------------------------
Windows.Data
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/system32/WinMetadata/Windows.Data.winmd
----------------------------------------
Windows.UI
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
NHotkey.WindowsForms
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.1.0.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/NHotkey.WindowsForms.DLL
----------------------------------------
AudioSwitcher.AudioApi.CoreAudio
    Version de l'assembly : 4.0.0.308
    Version Win32 : 4.0.0.308
    CodeBase : file:///C:/Program%20Files/DisplayMagician/AudioSwitcher.AudioApi.CoreAudio.DLL
----------------------------------------
AudioSwitcher.AudioApi
    Version de l'assembly : 4.0.0.308
    Version Win32 : 4.0.0.308
    CodeBase : file:///C:/Program%20Files/DisplayMagician/AudioSwitcher.AudioApi.DLL
----------------------------------------
ImageListView
    Version de l'assembly : 13.8.2.0
    Version Win32 : 13.8.2.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/ImageListView.DLL
----------------------------------------
IconLib
    Version de l'assembly : 0.73.0.0
    Version Win32 : 0.73.0.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/IconLib.DLL
----------------------------------------
IconExtractor
    Version de l'assembly : 1.0.3.0
    Version Win32 : 1.0.3.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/IconExtractor.DLL
----------------------------------------
MintPlayer.IconUtils
    Version de l'assembly : 1.0.4.0
    Version Win32 : 1.0.4.0
    CodeBase : file:///C:/Program%20Files/DisplayMagician/MintPlayer.IconUtils.DLL
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 4.0.0.1
    Version Win32 : 4.6.26919.02
    CodeBase : file:///C:/Program%20Files/DisplayMagician/System.Drawing.Common.DLL
----------------------------------------
System.Reflection.Emit.Lightweight
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Emit.Lightweight/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Emit.ILGeneration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
WinCopies.WindowsAPICodePack.Win32Native
    Version de l'assembly : 2.0.0.6
    Version Win32 : 2.0.0.6
    CodeBase : file:///C:/Program%20Files/DisplayMagician/WinCopies.WindowsAPICodePack.Win32Native.DLL
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4084.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

Interesting fact, DM is able to save the current default profile even if the error message is present. See attachement for the support zip file.

I will be out of town for a couple of days.

Thank you and have a nice weekend!
![no icon on default profile](https://user-images.githubusercontent.com/29050341/163575653-73f5865f-137d-454f-bc63-7411bee36cd5.PNG)
![error](https://user-images.githubusercontent.com/29050341/163575656-971d8940-fe67-4c85-9b10-3b4878fd7422.PNG)
[DisplayMagician-Support-20220415-0917.zip](https://github.com/terrymacdonald/DisplayMagician/files/8496086/DisplayMagician-Support-20220415-0917.zip)

**Comment by sk666** [comment]
hi Terry,

little update with the 2.3.1.12 (and may be with 2.3.1.7 also). This version break my shell explorer when I do a right click on my desktop, than it crash my file explorer to reload it. I can not have my right click desktop menu with this version. Works well with 2.3.0.36 build so I need to revert back to a previous version of DM to resolve this issue. But as you said in an other bug trhread, 2.3.1.12 resolved my issue when I create a new default profile display, so it's not bad at all (many thanks for this fix).

2.3.0.36 also resolve a part of my missing icon in DM of the profile section ( I now see the grey and blue monitor  in the middle of the page but it is blank on the icon at the bottom of the same page as you can see in this attachement. I can live with this problem, it dosen't affect DM at all, it is just for your personnal information.

thank you

![partially broken icon in 2 3 0 36](https://user-images.githubusercontent.com/29050341/163815064-1dd57d4c-b0f0-44f5-a672-53b4b4ea992c.PNG)

**Comment by terrymacdonald** [comment]
@sk666 Please try DisplayMagician 2.3.1.26 attached here. This is the almost latest test build and should hopefully fix your issues. You will need to delete you old display profiles, and create them again. It *should* work then. If not, please reply with details on what's broken, and we'll see what else needs to be fixed.

[DisplayMagicianSetup-v2.3.1.26.zip](https://github.com/terrymacdonald/DisplayMagician/files/8508386/DisplayMagicianSetup-v2.3.1.26.zip)

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

thank you for the fast answer. Build 2.3.1.26 is a huge improvement, it fix all of my previous problem. I think that the missing icon was the cause of the crash when I did a right click on the desktop because this icon is present in the desktop context menu.

I don't know if this is a bug or if it's intended (it's only for your information and I dont personally need a fix for that), I noticed that the surround icon over the desktop icon of the game is "higher" than the previous version ( it was as the bottom of the game shortcut icon in the previous version). I did not see other changes instead of that or any bug, good job :) I think you can close this ticket.

Thank you again for all of this work and fix :)

FYI, this is what I saw:
![surround icon](https://user-images.githubusercontent.com/29050341/163902826-b5c67217-48c3-418a-a1c1-760ba0e514e6.PNG)

**Comment by terrymacdonald** [comment]
Cool! If everything is fixed please close the issue.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oh BTW, I'll take a look at the alignment thing as a separate internal thing. Thanks for the heads up about it though!

**Comment by terrymacdonald** [comment]
@sk666 I have worked through many issues over the last week, so I recommend that you do some testing with this version:
[DisplayMagicianSetup-v2.3.1.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8512144/DisplayMagicianSetup-v2.3.1.50.zip)

This should also fix the image alignment in desktop shortcut icons you found. Turned out I needed to rewrite some more image generation logic 🙄. Should be fixed now, and actually is simpler than it was in the past so less chances for errors.

I **strongly** recommend that  you delete your old display profiles and recreate them again just to be 100% sure you're running the latest versions of the file, and then updated your game shortcuts to use those new profiles.

This version fixes all the bugs that I know about, and based on my testing is just about ready to release to the general public. I'd really appreciate it if you could do some testing (but only if you have some spare time) so that I will know if it really does fix all the issues.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi  @sk666,


The profile image is created when the display profile is created, and
doesn't get updated again. So can you please delete the Surround profile
from DisplayMagician, and then create it again? I think it might work this
time correctly.... Please see if it is green in the display profiles window
(and take a screenshot again please).

And then please edit your ATS game shortcut to use the new surround
profile, and see if it is now back to green. Please also take a screenshot
for the game shortcut window again too.

And lastly then try and save a desktop shortcut to. Check that it correctly
saves as a green surround again.

Thanks for your help testing!

Terry

**Comment by sk666** [comment]
Hi Terry,

i did it and same behavior. I give you the support log in case that you want to fix it but it's not ma

ndatory in my case. I'm very happy with this version and I can live with that without any problems.

Thank you

**Comment by terrymacdonald** [comment]
Hi @sk666,

You might be able to live with it broken but I can't ;). 

I've found the issue, and corrected it. This version should fix all the errors (but only will do so when you create a new display profile and have edited a shortcut using that profile). I've tested it and it works. If you could do these last tests then report back that would be really helpful.

[DisplayMagicianSetup-v2.3.1.56.zip](https://github.com/terrymacdonald/DisplayMagician/files/8516635/DisplayMagicianSetup-v2.3.1.56.zip)

As your underlying issue is fixed I will close this case.

Thanks
Terry

**Comment by sk666** [comment]
Hi Terry,

don,t know if it's ok to right this here but I just wanna say that 2.3.1.56 works fine. I tried everything that I use and could not "broke" it and I did not see any bug so I think it can be the next official build for everyone.

Let me know in the futur if I can test something for you, I will be more than happy to assist you. Just tag my name in the post that you need my help.

Thank you again, you did an amazing job!

**Comment by terrymacdonald** [comment]
Aww thanks for the kind words. I really like helping everyone out. I hope
that it makes everyone's life so much simpler.

Thanks
Terry
